version: "3"

networks:
  whaticket:

services:
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    environment:
      - DB_HOST=postgres
      - DB_USER=${DB_USER:-postgres}
      - DB_PASS=${DB_PASS:-lipao2002}
      - DB_NAME=${DB_NAME:-whaticket}
      - DB_PORT=5432
      - JWT_SECRET=${JWT_SECRET:-3123123213123}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET:-75756756756}
      - BACKEND_URL=${BACKEND_URL:-http://localhost}
      - FRONTEND_URL=${FRONTEND_URLs:-http://localhost:3001}
      - PROXY_PORT=${PROXY_PORT:-3030}
      - CHROME_ARGS=--no-sandbox --disable-setuid-sandbox
    ports:
      - ${BACKEND_PORT:-3030}:3000
    volumes:
      - ./backend/public/:/usr/src/app/public/
      - ./backend/.wwebjs_auth/:/usr/src/app/.wwebjs_auth/
    networks:
      - whaticket

  frontend:
    ports:
      - ${FRONTEND_PORT:-3001}:80
      - ${FRONTEND_SSL_PORT:-3002}:443
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    environment:
      - URL_BACKEND=backend:3000
      - REACT_APP_BACKEND_URL=${BACKEND_URL:-http://localhost}:${PROXY_PORT:-3030}/
      - FRONTEND_SERVER_NAME=${FRONTEND_SERVER_NAME}
      - BACKEND_SERVER_NAME=${BACKEND_SERVER_NAME}
    volumes:
      - ./ssl/certs/:/etc/nginx/ssl/
      - ./ssl/www/:/var/www/letsencrypt/
    networks:
      - whaticket

  postgres:
    image: ${DB_ENGINE:-postgres}:${DB_VERSION:-latest}
    volumes:
      - ./.docker/data/:/var/lib/postgresql
    environment:
      - POSTGRES_DB=${DB_NAME:-whaticket}
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASS:-lipao2002}
    ports:
      - ${HOST_PORT:-5433}:5432
    restart: always
    networks:
      - whaticket
